SUPABASE_URL = "https://lhxmpxlbbrafjrpmkvov.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoeG1weGxiYnJhZmpycG1rdm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Nzg2ODgsImV4cCI6MjA3NDU1NDY4OH0.OMtBHEYF64x-FpBA8u42MAJ4yYrz0bZbbtb8INWsqbM"

